#!/bin/bash

mkdir -p ~/.local/bin
cp autoenv-rs ~/.local/bin/

mkdir -p ~/.autoenv-rs
cp autoenv_rs_cd ~/.autoenv-rs/

echo
echo Add the following lines to your .bashrc:
echo
echo "    source ~/.autoenv-rs/bash_autocd"
echo "    alias cd=__autoenv_rs_cd__"

echo
echo then run:
echo
echo "    source ~/.bashrc"
echo
